export { default as Seo } from "./seo";
export { default as Logo } from "./logo";
export { default as Home } from "./home";
export { default as FeaturesSection } from "./featuresSection";
export { default as DownloadSection } from "./downloadSection";
export { default as FAQsSection } from "./fAQsSection";
export { default as Accordion } from "./accordion";
export { default as ContactSection } from "./contactSection";
export { default as HomePageFooter } from "./homePageFooter";